modLoader="javafml" 
loaderVersion="[44,)" 
license="MIT License"
issueTrackerURL="https://github.com/TheMillman/FarmingUtils/issues" 

[[mods]] 
modId="farmingutils"
version="${file.jarVersion}" 
displayName="Farming Utils"
updateJSONURL="https://raw.githubusercontent.com/TheMillman/FarmingUtils/1.18.1/update.json" 
displayURL="https://www.curseforge.com/minecraft/mc-mods/farmingutils" 
logoFile="logo.png" 
authors="The_Millman"
description='''
This mod adds different blocks and items for a easy way to farming resources in Minecraft.
'''

[[dependencies.farmingutils]] 
    modId="forge" 
    mandatory=true 
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.farmingutils]] 
    modId="themillmanlib" 
    mandatory=true 
    versionRange="[1.19.3-0.1.12,1.19.3-0.1.13)"
    ordering="NONE"
    side="BOTH"    

[[dependencies.farmingutils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
