modLoader="javafml" 
loaderVersion="${loader_version_range}" 
license="${mod_license}"
issueTrackerURL="https://github.com/TheMillman/FarmingUtils/issues" 

[[mods]] 
modId="${mod_id}"
version="${mod_version}" 
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/TheMillman/FarmingUtils/1.19.2/update.json" 
displayURL="https://www.curseforge.com/minecraft/mc-mods/farmingutils" 
logoFile="logo.png" 
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]] 
    modId="forge" 
    mandatory=true 
    versionRange="${loader_version_range}"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.${mod_id}]] 
    modId="themillmanlib" 
    mandatory=true 
    versionRange="${lib_version_range}"
    ordering="NONE"
    side="BOTH"    

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
